# Generated by Django 4.1.1 on 2022-10-03 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='adRespons',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ad_board.ad'),
            preserve_default=False,
        ),
    ]
