# Generated by Django 4.1.1 on 2022-10-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_board', '0002_response_adrespons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='authorName',
            field=models.CharField(max_length=64),
        ),
    ]
